### ISSUE TITLE
Upgrade to OJS 3.2

### ISSUE THREAD

**Issue by ZahraMousavi** [ojsde/shariff#18]
Hi guys. Shariff plugin breaks in our OJS 3.2. We know that there is not a version suited for OJS 3.2 yet, but do you have any plan for upgrading the plugin?

**Comment by ronste** [comment]
Hi Zahra,

currently we unfortunately lack the personnel capacities to upgrade Plugins to OJS 3.2. We hope this will change by the beginning of next year at the latest. We will start upgrading plugins to OJS 3.2 as soon as our capacities allow for it.

Best wishes,
Ronald

**Comment by ZahraMousavi** [comment]
Thanks for the quick response! We like your plugin a lot and there are several of our journals that use it. We really hope that you get the time to upgrade it as soon as possible.

All the best,
Zahra

**Comment by majaroenne** [comment]
Hi Ronald
I'm a developer working the Royal Danish Library together with Zahra Mousavi
I have made minor changes to make shariff work with ojs 3.2

I would like to make a pull-request with my changes but I think I need a new branch in shariff the make the pull request against
Can you please make the proper branch 
Best regards
Maja Rønne

**Comment by ronste** [comment]
Hi Maja  Rønne,

many thanks for contributing !!!

I created a branch dev-ojs-3_2 from master. Before I incorporate your changes into master I will test it against my local OJS 3.2 installation. Once this is done we can make an official release for 3.2.

Best wishes,
Ronald
