### ISSUE TITLE
base_url override settings ignored

### ISSUE THREAD

**Issue by klausru** [ojsde/shariff#2]
Dear Božana Bokan

it seems that the plugin ignores the base_url override settings declared in config.inc.php

I`m using the plugin on www.medienpaed.com and the URLs contain the install path, which should not be shown due to the base_url override settings.
Maybe the problem is the construction of the URLs via $requestedUrl and getCompleteUrl() . Are there any workarounds or alternative methods to contruct the URL?

Thanks

**Comment by bozana** [comment]
Hi @klausru, thanks a lot for reporting this -- I will try to fix it...

**Comment by klausru** [comment]
Thanks for having a look at it.
As a quick and dirty workaround I replaced the `$requestedUrl` in ShariffBlockPlugin.inc.php by:
`$currentUrl = "//{$_SERVER['HTTP_HOST']}{$_SERVER['REQUEST_URI']}";`
and called that with `data-url="{$currentUrl|escape}">` in the /templates/shariffBlock.tpl
Although it works, I do not know whether this might cause security problems.
