### ISSUE TITLE
Error 500 upon plugin upload

### ISSUE THREAD

**Issue by sushantvirdi** [ojsde/shariff#21]
Hi!

I am running OJS 3.1.2 and as soon as I uploaded and activated the plugin, the whole website went down and started showing a 500 Error. I then had to rename the plugin fodler to get the site back up and running. I dig up the logs and they say this:

`[Mon Oct 12 10:29:20.032690 2020] [:error] [pid 19769] [client 109.177.14.16:55886] PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /var/www/html/plugins/generic/shariff/ShariffPlugin.inc.php:42\nStack trace:\n#0 /var/www/html/lib/pkp/classes/plugins/PluginRegistry.inc.php(65): ShariffPlugin->register('generic', 'plugins/generic...', NULL)\n#1 /var/www/html/lib/pkp/classes/plugins/PluginRegistry.inc.php(138): PluginRegistry::register('generic', Object(ShariffPlugin), 'plugins/generic...', NULL)\n#2 /var/www/html/lib/pkp/classes/core/Dispatcher.inc.php(132): PluginRegistry::loadCategory('generic', true)\n#3 /var/www/html/lib/pkp/classes/core/PKPApplication.inc.php(252): Dispatcher->dispatch(Object(Request))\n#4 /var/www/html/index.php(68): PKPApplication->execute()\n#5 {main}\n  thrown in /var/www/html/plugins/generic/shariff/ShariffPlugin.inc.php on line 42`

What could be the issue here?

**Comment by ronste** [comment]
Hi sushantvirdi,

to help you with this issue I require more information.

How did you install the plugin? Did you download a release package or did you use git?
If you downloaded a release package. Did you install it from inside OJS backend or did you manually install it?
If you manually installed the package. Did you run the installPluginVersion script afterwards?
If you used git. Did you checkout the correct branch?
What is the version number in the file version.xml in the plugin folder?

Best wishes,
Ronald

**Comment by sushantvirdi** [comment]
Hi Ronald, 

Thanks for responding back. I used the file from here and directly uploaded from the OJS backend: https://github.com/ojsde/shariff/releases/download/v3_1_2/shariff-3.1.2.tar.gz

After installing it, I made a mistake of enabling it on the index site which I guess broke the website. I read about a person having a similar issue here and even deleted the same row but even that did not help. https://github.com/ojsde/shariff/issues/13

Thanks!

**Comment by ronste** [comment]
Hi sushantvirdi,

I see what you mean. I'll have to look into this on my test server. Unfortunately I don't have much spare time to spend for this. I'll put it on my to do list.

Could you fix the issue by enabling it for a single journal only?

**Comment by sushantvirdi** [comment]
Hi Ronald, 

I understand that. Thanks!

Just wanted to check if it's possible to remove the plugin completely from the database as I currently see it's still enabled for the index page, despite removing from the backend. 

Thanks!
