### ISSUE TITLE
Funktioniert nicht mit OJS 3.2.1.1

### ISSUE THREAD

**Issue by mpbraendle** [ojsde/shariff#22]
- taucht nicht auf in der Plugin-Gallery
- manuelle Installation via tar.gz in /plugins/generic/ --> Plugin erscheint nicht in der Plugin-Liste

Fehler:

Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getSubmissionId() on null in /var/www/virtual/devojs.chimia.ch/htdocs/ojs/lib/pkp/controllers/grid/notifications/NotificationsGridCellProvider.inc.php:118\nStack trace:\n#0 /var/www/virtual/devojs.chimia.ch/htdocs/ojs/lib/pkp/controllers/grid/notifications/NotificationsGridCellProvider.inc.php(44): NotificationsGridCellProvider->_getTitle(Object(Notification))\n#1 /var/www/virtual/devojs.chimia.ch/htdocs/ojs/lib/pkp/classes/controllers/grid/GridCellProvider.inc.php(56): NotificationsGridCellProvider->getCellActions(Object(Request), Object(GridRow), Object(GridColumn))\n#2 /var/www/virtual/devojs.chimia.ch/htdocs/ojs/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1104): GridCellProvider->render(Object(Request), Object(GridRow), Object(GridColumn))\n#3 /var/www/virtual/devojs.chimia.ch/htdocs/ojs/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1011): GridHandler->_renderCellInternally(Object(Request), Object(GridRow), Obj...', referer: https://devojs.chimia.ch/management/settings/website

**Comment by mpbraendle** [comment]
Vergleich mit anderen OJS 3.2.1-1 generic plugins: alle functions sind public, bei Shariff aber nicht.

**Comment by ohilbig01** [comment]
Hallo,
ich hatte das Problem auch, es liegt am Rückgabewert der Funktion register() in ShariffPlugin.inc.php().
Ich versuche mal, einen pull request zu machen.

**Comment by ronste** [comment]
>     * taucht nicht auf in der Plugin-Gallery
>

Das Shariff-Plugin ist derzeit nicht Teil der PKP Plugin-Gallery von OJS 3.2. Es kann daher nur manuell installiert werden.
 
>     * manuelle Installation via tar.gz in /plugins/generic/ --> Plugin erscheint nicht in der Plugin-Liste
> 

Da wir bisher kein tar.gz-Release für OJS 3.2 veröffentlicht haben ist mir momentan nicht klar woher die tar.gz-Datei kommt die Sie versucht haben zu installieren. Der letzte Release ist für OJS 3.1.1/3.1.2. Ich werde versuchen sobald wie möglich ein Release für OJS 3.2 zu veröffentlichen.

Bis dahin können Sie entweder das Git-Repo klonen und den Branch "_stable-3_2_1_" verwenden, oder Sie laden sich die zip-Datei runter (https://github.com/ojsde/shariff -> Code -> Download zip), bennenen den Ordner "_shariff-master_" in "_shariff_" um und kopieren den extrahierten Ordner in den Ordner "_plugins/generic_".
Das Plugin sollte dann in OJS unter "_Installierte Plugins_" erscheinen.

**Comment by mpbraendle** [comment]
Das tar.gz habe ich aus dem Master hergestellt. 

"Der letzte Release ist für OJS 3.1.1/3.1.2."
Ich ging davon aus, dass wenn in der README.md steht, "This plugin has been tested with OJS version 3.2.1!", dass das verwendbar sei. @ohilbig01 hat einen Pull-Request z.V. gestellt.

**Comment by ronste** [comment]
> Das tar.gz habe ich aus dem Master hergestellt.
>

Ok, das sollte theoretisch (aber siehe Kommentar unten) funktionieren solange der Ordner und "_shariff_" umbenannt wurde.
 
> "Der letzte Release ist für OJS 3.1.1/3.1.2."
> Ich ging davon aus, dass wenn in der README.md steht, "This plugin has been tested with OJS version 3.2.1!", dass das verwendbar sei. @ohilbig01 hat einen Pull-Request z.V. gestellt.

Das ist völlig korrekt. Die README.md bezieht sich auf den Stand des master-Branches im Repo und dieser läuft bereits auf verschiedenen OJS 3.2 Installationen (wurde da aber immer via git installiert).
Die Releases beziehen sich immer auf die in der Releasebeschreibung angegebenen Versionen, i.e. 3.1.1/3.1.2.

Allerdings scheint es bei einem aus dem master-Branch erstellten Installationspaket Probleme bei verschiedenen Installationswegen zu geben. Wir können da leider nicht alle möglichen Kombinationen testen.
Ich konnte diese Probleme jetzt bei mir nachvollziehen und werde versuchen das so schnell wie möglich zu beheben. Den Pull-Request werde ich dabei natürlich auch berücksichtigen.

**Comment by mpbraendle** [comment]
Danke, konnte das Plugin mit den neuesten Änderungen installiert und das funktioniert nun mit OJS 3.2.1
