### ISSUE TITLE
Adressierbares div-Element für Seitenblock bzw. Artikeldetailseite

### ISSUE THREAD

**Issue by mpbraendle** [ojsde/shariff#24]
Empfehlung für Zeile 124 von ShariffPlugin.inc.php , ein mit einer Klasse versehenes div-Element zu verwenden:

Z.B. anstelle von `$divWrapper = '<div><div>';`

`$divWrapper = '<div class="shariffblock"><div>'; `

verwenden.

Damit kann das div-Element geeignet mit CSS adressiert werden. Beispielsweise lässt sich dann mit CSS flexbox die Anordung des Elements auf der Artikeldetailseite beliebig setzen.

Beispiel: https://doi.org/10.26043/GISo.2020.1.3 --> Shariffblock ist an vierter Stelle anstatt am Ende der Artikeldetails.

**Comment by ronste** [comment]
Danke für die Empfehlung. Ich habe das entsprechend eingebaut.
Ich werde sobald ich dazu komme dann offizielle Release-Pakete für OJS 3.2 erstellen.
