### ISSUE TITLE
Not compatible with 3.4.0? 500 internal server error

### ISSUE THREAD

**Issue by wrapper** [ojsde/shariff#30]
After installing this plugin I get a WSOD when navigating to the /settings/website page

**Comment by ronste** [comment]
Your conclusion is completely correct.

OJS 3.4 has not been released yet. So up to now there is no upgrade for the plugin.

**Comment by wrapper** [comment]
Oh I see.. I didn't intentionally install a newer version.

Seems strange to me that a point update should be plugin breaking, but I don't know much about this system.

Thanks
