### ISSUE TITLE
Improve to Documentation

### ISSUE THREAD

**Issue by hilongo** [ojsde/shariff#33]
Hello there .. I have installed this plugin on OJS 3.3.0-14 and had a little problem finding where to configure it, as usually OJS plugins are configured from the Installed Plugin list and this one is not. This discrepancy is not reflected in the README.md file's Settings section (https://github.com/ojsde/shariff#settings)

There should be a mention there that says that the plugin creates a new **Shariff Plugin** Tab under Settings -> Appearence from where you can configure it.

Thanks a lot!

**Comment by ronste** [comment]
Hi @hilongo ,

Thanks for the hint. I updated the Readme.

Best wishes,
Ronald
