### ISSUE TITLE
Missing locale key for settings success message - OJS 3.4

### ISSUE THREAD

**Issue by israelcefrin** [ojsde/shariff#34]
There is a missing locale key on the version released for OJS3.4.
Everytime the dashboard loads , the webserver error log file returns:

`Missing locale key "plugins.generic.shariff.settings.form.success" for the locale "en"`

The key is missing in `en` locale PO file, but I assume it is worth the while to check all locale files.

**Comment by ronste** [comment]
Hi @israelcefrin ,

thanks for reporting this. Indeed this locale is not used anymore and I just forgot to remove one reference to it.

I will fix this with the next version.

Best wishes,
Ronald
