### ISSUE TITLE
Email body being filled with a variable instead of the link (stable-3_4_0)

### ISSUE THREAD

**Issue by iudizm** [ojsde/shariff#39]
When sharing an article form an OJS 3.4 using the plugin from `stable-3_4_0` branch,
the email body is being filled with a Smarty-like call to `$requestedUrl|escape`.

Example:

![email-body-bug](https://github.com/ojsde/shariff/assets/43123002/2141df16-9de1-4ddf-8e1c-886932865036)

[This line](https://github.com/ojsde/shariff/blob/fa56ae0c8c3ea2d99d5f88ae52eebde1fac45f21/ShariffPlugin.inc.php#L256) is responsible for it.

**Comment by ronste** [comment]
Gallery PR created: https://github.com/pkp/plugin-gallery/pull/271
